"""add sending engine schema updates

Revision ID: 0f3251e8c547
Revises: a1c9d7e8f234
Create Date: 2026-04-27 04:53:41.734812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f3251e8c547'
down_revision: Union[str, None] = 'a1c9d7e8f234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - manually tuned ###
    op.add_column('email_event', sa.Column('event_scope', sa.String(length=20), server_default=sa.text("'lead'"), nullable=False, comment='Event scope: lead | warmup.'))
    op.add_column('email_event', sa.Column('sender_account_id', sa.UUID(as_uuid=False), nullable=True, comment='FK to sender_account that originated this event.'))
    op.add_column('email_event', sa.Column('recipient_account_id', sa.UUID(as_uuid=False), nullable=True, comment='FK to recipient sender_account for warmup exchange events.'))
    op.add_column('email_event', sa.Column('warmup_thread_id', sa.UUID(as_uuid=False), nullable=True, comment='Correlation identifier for warmup message exchanges.'))
    op.alter_column('email_event', 'lead_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='FK to lead — set for lead-scope events, NULL for warmup-scope events.',
               existing_comment='FK to lead — which contact this event is about.')
    op.create_index('ix_email_event_lead_occurred_at', 'email_event', ['lead_id', 'occurred_at'], unique=False)
    op.create_index('ix_email_event_scope_occurred_at', 'email_event', ['event_scope', 'occurred_at'], unique=False)
    op.create_index('ix_email_event_sender_occurred_at', 'email_event', ['sender_account_id', 'occurred_at'], unique=False)
    op.create_index('ix_email_event_warmup_thread', 'email_event', ['warmup_thread_id'], unique=False)
    op.create_check_constraint(
        'ck_email_event_scope',
        'email_event',
        "event_scope IN ('lead','warmup')",
    )
    op.create_check_constraint(
        'ck_email_event_scope_shape',
        'email_event',
        "("
        "(event_scope = 'lead' AND lead_id IS NOT NULL)"
        " OR "
        "(event_scope = 'warmup' AND lead_id IS NULL AND sender_account_id IS NOT NULL)"
        ")",
    )
    op.create_foreign_key(op.f('fk_email_event_recipient_account_id_sender_account'), 'email_event', 'sender_account', ['recipient_account_id'], ['account_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_email_event_sender_account_id_sender_account'), 'email_event', 'sender_account', ['sender_account_id'], ['account_id'], ondelete='SET NULL')
    op.add_column('lead', sa.Column('next_step_id', sa.UUID(as_uuid=False), nullable=True, comment='FK to sequence_step — the next step due for this lead.'))
    op.create_index('ix_lead_next_step_id', 'lead', ['next_step_id'], unique=False)
    op.create_foreign_key(op.f('fk_lead_next_step_id_sequence_step'), 'lead', 'sequence_step', ['next_step_id'], ['step_id'], ondelete='SET NULL')
    op.add_column('warmup_settings', sa.Column('warmup_started_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='UTC timestamp used as day-0 anchor for warm-up ramp calculations.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - manually tuned ###
    op.drop_column('warmup_settings', 'warmup_started_at')
    op.drop_constraint(op.f('fk_lead_next_step_id_sequence_step'), 'lead', type_='foreignkey')
    op.drop_index('ix_lead_next_step_id', table_name='lead')
    op.drop_column('lead', 'next_step_id')
    op.drop_constraint(op.f('fk_email_event_sender_account_id_sender_account'), 'email_event', type_='foreignkey')
    op.drop_constraint(op.f('fk_email_event_recipient_account_id_sender_account'), 'email_event', type_='foreignkey')
    op.drop_constraint('ck_email_event_scope_shape', 'email_event', type_='check')
    op.drop_constraint('ck_email_event_scope', 'email_event', type_='check')
    op.drop_index('ix_email_event_warmup_thread', table_name='email_event')
    op.drop_index('ix_email_event_sender_occurred_at', table_name='email_event')
    op.drop_index('ix_email_event_scope_occurred_at', table_name='email_event')
    op.drop_index('ix_email_event_lead_occurred_at', table_name='email_event')
    op.alter_column('email_event', 'lead_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='FK to lead — which contact this event is about.',
               existing_comment='FK to lead — set for lead-scope events, NULL for warmup-scope events.')
    op.drop_column('email_event', 'warmup_thread_id')
    op.drop_column('email_event', 'recipient_account_id')
    op.drop_column('email_event', 'sender_account_id')
    op.drop_column('email_event', 'event_scope')
    # ### end Alembic commands ###
