"""add reset password attributes in LocalAuth

Revision ID: 2114242a444d
Revises: df619de6aa36
Create Date: 2026-04-23 17:16:13.526293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2114242a444d'
down_revision: Union[str, None] = 'df619de6aa36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_auth', sa.Column('reset_token', sa.String(length=255), nullable=True, comment='One-time token sent in the password reset email.'))
    op.add_column('local_auth', sa.Column('reset_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='Expiry time for the password reset token.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_auth', 'reset_expires_at')
    op.drop_column('local_auth', 'reset_token')
    # ### end Alembic commands ###
