"""s1_s3_s5_s6_s7_schema_additions

Revision ID: 764aa51766e6
Revises: 2114242a444d
Create Date: 2026-04-25 17:51:12.895392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '764aa51766e6'
down_revision: Union[str, None] = '2114242a444d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('log_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier for this audit log entry.'),
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=True, comment='FK to workspace — NULL if the workspace has since been deleted.'),
    sa.Column('actor_user_id', sa.UUID(as_uuid=False), nullable=True, comment='FK to users — the user who triggered this event. NULL if user deleted.'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='Machine-readable action name e.g. role_changed, campaign_started.'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='Type of affected entity: collaborator | campaign | invitation.'),
    sa.Column('target_id', sa.UUID(as_uuid=False), nullable=True, comment='UUID of the affected entity at the time of the event.'),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSONB snapshot of the entity state before this action.'),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSONB snapshot of the entity state after this action.'),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when this event was recorded.'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('invitation',
    sa.Column('invitation_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier for this invitation record.'),
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False, comment='FK to workspace — which workspace this invitation grants access to.'),
    sa.Column('invited_by', sa.UUID(as_uuid=False), nullable=False, comment='FK to users — the member who created this invitation.'),
    sa.Column('invitee_email', sa.String(length=255), nullable=False, comment='Email address the invitation was sent to.'),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=False, comment='FK to role — the role offered to the invitee.'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='Cryptographically-random URL-safe token for accepting this invitation.'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False, comment='Lifecycle state: pending | accepted | declined | cancelled | expired.'),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False, comment='UTC expiry time — tokens presented after this are rejected.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when this invitation was created.'),
    sa.Column('responded_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='UTC timestamp when the invitee accepted or declined.'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invitation_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('campaign_run',
    sa.Column('run_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier for this execution event.'),
    sa.Column('campaign_id', sa.UUID(as_uuid=False), nullable=False, comment='FK to campaign — which campaign this event belongs to.'),
    sa.Column('triggered_by', sa.UUID(as_uuid=False), nullable=True, comment='FK to users — who triggered this transition. NULL for automated events.'),
    sa.Column('action', sa.String(length=30), nullable=False, comment='The lifecycle action performed: started | paused | resumed | stopped | completed.'),
    sa.Column('run_status', sa.String(length=30), nullable=False, comment='Campaign status after this action: running | paused | stopped | completed | error.'),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment="UTC timestamp when sending began for this run (set on 'started' action)."),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='UTC timestamp when this run ended (set on stopped/completed/error).'),
    sa.Column('error_message', sa.Text(), nullable=True, comment="Error description when run_status is 'error'."),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when this run record was created.'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('lead_import_session',
    sa.Column('session_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier for this import session.'),
    sa.Column('campaign_id', sa.UUID(as_uuid=False), nullable=False, comment='FK to campaign — which campaign these leads were uploaded to.'),
    sa.Column('imported_by', sa.UUID(as_uuid=False), nullable=False, comment='FK to users — the user who triggered this import.'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment="Original filename of the uploaded file (e.g. 'leads_q2.csv')."),
    sa.Column('row_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Total rows parsed from the file (header excluded).'),
    sa.Column('imported_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Rows successfully written to the lead table.'),
    sa.Column('skipped_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Rows skipped due to duplicate email (uq_lead_campaign_email violation).'),
    sa.Column('error_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Rows rejected due to validation errors (not written to lead table).'),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSONB array of per-row errors: [{"row": N, "email": "...", "reason": "..."}].'),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'processing'"), nullable=False, comment='Import job state: processing | completed | failed.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when this import session was created.'),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='UTC timestamp when parsing finished (success or failure).'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['imported_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('step_email',
    sa.Column('email_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier for this email variant.'),
    sa.Column('step_id', sa.UUID(as_uuid=False), nullable=False, comment='FK to sequence_step — the step this variant belongs to.'),
    sa.Column('subject_line', sa.String(length=998), nullable=False, comment='Email subject — supports {{merge_tag}} template variables.'),
    sa.Column('email_body', sa.Text(), nullable=False, comment='HTML or plain-text email body — supports {{merge_tag}} variables.'),
    sa.Column('from_name', sa.String(length=255), nullable=True, comment='Display name for the From header. NULL = use sender_account default.'),
    sa.Column('sender_account_id', sa.UUID(as_uuid=False), nullable=True, comment='FK to sender_account — NULL = rotation pool, set = pinned mailbox.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when this email variant was created.'),
    sa.ForeignKeyConstraint(['sender_account_id'], ['sender_account.account_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['step_id'], ['sequence_step.step_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.add_column('campaign', sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='UTC date-time when this campaign is scheduled to start sending.'))
    op.add_column('campaign', sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='UTC date-time after which no further emails are sent for this campaign.'))
    op.add_column('campaign', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='UTC timestamp of the most recent update to this campaign record.'))
    op.add_column('lead', sa.Column('import_session_id', sa.UUID(as_uuid=False), nullable=True, comment='FK to lead_import_session — NULL for manually added leads.'))
    op.create_foreign_key(
        'fk_lead_import_session_id',
        'lead',
        'lead_import_session',
        ['import_session_id'],
        ['session_id'],
        ondelete='SET NULL',
    )
    op.add_column('sequence_step', sa.Column('send_time', sa.String(length=5), nullable=True, comment='Step-level send time override (HH:MM, 24-hour). Overrides campaign.schedule.'))
    op.add_column('sequence_step', sa.Column('send_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Step-level send-day override — JSON array e.g. ["Monday","Wednesday"].'))
    op.alter_column('sequence_step', 'subject_line',
               existing_type=sa.VARCHAR(length=998),
               nullable=True,
               comment='DEPRECATED — use step_email.subject_line. Kept nullable during migration.',
               existing_comment='Email subject line for this step. Supports template variables.')
    op.alter_column('sequence_step', 'email_body',
               existing_type=sa.TEXT(),
               nullable=True,
               comment='DEPRECATED — use step_email.email_body. Kept nullable during migration.',
               existing_comment='HTML or plain-text body of the email. Supports template variables.')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sequence_step', 'email_body',
               existing_type=sa.TEXT(),
               nullable=False,
               comment='HTML or plain-text body of the email. Supports template variables.',
               existing_comment='DEPRECATED — use step_email.email_body. Kept nullable during migration.')
    op.alter_column('sequence_step', 'subject_line',
               existing_type=sa.VARCHAR(length=998),
               nullable=False,
               comment='Email subject line for this step. Supports template variables.',
               existing_comment='DEPRECATED — use step_email.subject_line. Kept nullable during migration.')
    op.drop_column('sequence_step', 'send_days')
    op.drop_column('sequence_step', 'send_time')
    op.execute(
        """
        DO $$
        DECLARE
            fk_name text;
        BEGIN
            SELECT c.conname
            INTO fk_name
            FROM pg_constraint c
            JOIN pg_class t ON t.oid = c.conrelid
            JOIN pg_namespace n ON n.oid = t.relnamespace
            WHERE c.contype = 'f'
              AND t.relname = 'lead'
              AND n.nspname = current_schema()
              AND c.confrelid = 'lead_import_session'::regclass
              AND c.conkey = ARRAY[
                    (
                        SELECT a.attnum
                        FROM pg_attribute a
                        WHERE a.attrelid = t.oid
                          AND a.attname = 'import_session_id'
                          AND NOT a.attisdropped
                        LIMIT 1
                    )
              ]::smallint[];

            IF fk_name IS NOT NULL THEN
                EXECUTE format('ALTER TABLE %I.%I DROP CONSTRAINT %I', current_schema(), 'lead', fk_name);
            END IF;
        END $$;
        """
    )
    op.drop_column('lead', 'import_session_id')
    op.drop_column('campaign', 'updated_at')
    op.drop_column('campaign', 'end_date')
    op.drop_column('campaign', 'start_date')
    op.drop_table('step_email')
    op.drop_table('lead_import_session')
    op.drop_table('campaign_run')
    op.drop_table('invitation')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
