"""initial schema

Revision ID: 89b1d1781340
Revises: 
Create Date: 2026-04-23 02:54:05.717295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89b1d1781340'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('role_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Surrogate PK for this role definition.'),
    sa.Column('role_name', sa.String(length=100), nullable=False, comment='Human-readable name of the role (e.g. Admin, Editor, Viewer).'),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='JSONB map of permission flags granted to holders of this role.'),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier for every user account.'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='Legal first name of the user.'),
    sa.Column('middle_name', sa.String(length=100), nullable=True, comment='Middle name — optional, not all users have one.'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='Legal last name / family name of the user.'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Primary email address — used for login and outbound communication.'),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment="Whether the user's email address has been verified."),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when this account was first created.'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('local_auth',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False, comment='Shared PK/FK with users — enforces 1:1 relationship.'),
    sa.Column('password_hash', sa.Text(), nullable=True, comment="Bcrypt or Argon2 hash of the user's password. Never plain-text."),
    sa.Column('verification_token', sa.String(length=255), nullable=True, comment='One-time token sent in the verification email.'),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='Expiry time for the email verification token.'),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='True once the user has clicked the email verification link.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('oauth_accounts',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Surrogate PK for this OAuth link record.'),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False, comment='FK to users — the CampaignPulse user who linked this account.'),
    sa.Column('provider_type', sa.String(length=50), nullable=False, comment='Name of the OAuth provider (google, microsoft, github, etc.).'),
    sa.Column('provider_id', sa.String(length=255), nullable=False, comment="Provider-assigned subject ID (the 'sub' claim in the ID token)."),
    sa.Column('access_token', sa.Text(), nullable=False, comment='OAuth access token. Rotate / encrypt as required by your security policy.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when this OAuth link was first created.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Surrogate PK for this refresh token record.'),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False, comment='FK to users — the session owner.'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of the refresh token. Never store the raw token.'),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False, comment='UTC expiry time — tokens presented after this are rejected.'),
    sa.Column('revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='If True, this token is invalid regardless of expiry time.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('workspace',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier for this workspace.'),
    sa.Column('workspace_name', sa.String(length=255), nullable=False, comment='Display name for the workspace.'),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False, comment='FK to users — workspace owner/admin. RESTRICT prevents orphaned workspaces.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when this workspace was created.'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('collaborator',
    sa.Column('member_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Surrogate PK identifying this workspace membership record.'),
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False, comment='FK to workspace — which workspace this membership belongs to.'),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False, comment='FK to users — which user holds this membership.'),
    sa.Column('invite_status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False, comment='Invitation lifecycle state: pending | accepted | declined.'),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='UTC timestamp when the user accepted the invitation. NULL if still pending.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('sender_account',
    sa.Column('account_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier for this sender account.'),
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False, comment='FK to workspace — which workspace owns this sender account.'),
    sa.Column('provider_type', sa.String(length=50), nullable=False, comment='Email provider type: smtp | google | microsoft.'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='The sender email address shown in the From header.'),
    sa.Column('smtp_host', sa.String(length=255), nullable=True, comment='SMTP server hostname (e.g. smtp.gmail.com).'),
    sa.Column('smtp_port', sa.Integer(), nullable=True, comment='SMTP server port (typically 587 for STARTTLS, 465 for SSL).'),
    sa.Column('imap_host', sa.String(length=255), nullable=True, comment='IMAP server hostname (e.g. imap.gmail.com).'),
    sa.Column('imap_port', sa.Integer(), nullable=True, comment='IMAP server port (typically 993 for SSL).'),
    sa.Column('app_password', sa.Text(), nullable=True, comment='SMTP/IMAP password or app-specific password. Encrypt at rest.'),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'active'"), nullable=False, comment='Account status: active | inactive | suspended | warming_up.'),
    sa.Column('daily_sending_limit', sa.Integer(), server_default=sa.text('100'), nullable=False, comment='Maximum number of emails this account may send in a 24-hour window.'),
    sa.Column('sent_count_today', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Running count of emails sent today. Reset daily by the scheduler.'),
    sa.Column('min_delay_seconds', sa.Integer(), server_default=sa.text('60'), nullable=False, comment='Minimum seconds to wait between consecutive sends from this account.'),
    sa.Column('max_imap_fetch', sa.Integer(), nullable=True, comment='Maximum number of IMAP messages to fetch per reply-detection cycle.'),
    sa.Column('last_imap_uid', sa.BigInteger(), nullable=True, comment='IMAP UID cursor — the last processed message UID. Enables incremental fetch.'),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='UTC timestamp of the most recent send from this account.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when this sender account was added.'),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='True once SMTP/IMAP credentials have been validated by the system.'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('campaign',
    sa.Column('campaign_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier for this campaign.'),
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False, comment='FK to workspace — every campaign belongs to exactly one workspace.'),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True, comment='FK to collaborator — which workspace member created this campaign.'),
    sa.Column('campaign_name', sa.String(length=255), nullable=False, comment="Display name for the campaign (e.g. 'Q2 2026 SaaS Outreach')."),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'draft'"), nullable=False, comment='Lifecycle state: draft | active | paused | completed | archived.'),
    sa.Column('timezone', sa.String(length=100), server_default=sa.text("'UTC'"), nullable=False, comment='IANA timezone string governing when this campaign sends emails.'),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSONB object describing the permitted sending window for this campaign.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when this campaign was created.'),
    sa.ForeignKeyConstraint(['created_by'], ['collaborator.member_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_table('collaborator_role',
    sa.Column('member_id', sa.UUID(as_uuid=False), nullable=False, comment='Part of composite PK. FK to collaborator.'),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=False, comment='Part of composite PK. FK to role.'),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when this role was assigned to the collaborator.'),
    sa.Column('assigned_by', sa.UUID(as_uuid=False), nullable=True, comment='UUID of the user who performed this role assignment (audit trail).'),
    sa.ForeignKeyConstraint(['member_id'], ['collaborator.member_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', 'role_id')
    )
    op.create_table('warmup_settings',
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False, comment='Shared PK/FK with sender_account — enforces 1:1 relationship.'),
    sa.Column('is_warmup_active', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='When True, the warm-up scheduler controls daily send volume for this account.'),
    sa.Column('start_mail_rate', sa.Numeric(precision=8, scale=2), server_default=sa.text('5'), nullable=False, comment='Number of emails to send on day 1 of the warm-up schedule.'),
    sa.Column('daily_max_emails', sa.Integer(), server_default=sa.text('50'), nullable=False, comment='Hard ceiling on daily sends during the warm-up period.'),
    sa.Column('ramp_up_rate', sa.Numeric(precision=5, scale=2), server_default=sa.text('1.5'), nullable=False, comment='Daily growth multiplier for warm-up volume (e.g. 1.5 = +50%/day).'),
    sa.ForeignKeyConstraint(['account_id'], ['sender_account.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('lead',
    sa.Column('lead_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier for this lead record.'),
    sa.Column('campaign_id', sa.UUID(as_uuid=False), nullable=False, comment='FK to campaign — the campaign this lead is enrolled in.'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email address of the lead. The primary delivery address.'),
    sa.Column('first_name', sa.String(length=100), nullable=True, comment="Lead's first name — used in email personalisation merge tags."),
    sa.Column('last_name', sa.String(length=100), nullable=True, comment="Lead's last name."),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='Company the lead works for — used in personalisation and filtering.'),
    sa.Column('custom_variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True, comment='JSONB map of custom merge-tag values (e.g. job_title, industry).'),
    sa.Column('lead_status', sa.String(length=30), server_default=sa.text("'active'"), nullable=False, comment='Outreach funnel status: active | replied | unsubscribed | bounced | completed.'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_table('sequence_step',
    sa.Column('step_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Surrogate UUID PK introduced per 1NF normalisation.'),
    sa.Column('campaign_id', sa.UUID(as_uuid=False), nullable=False, comment='FK to campaign — which campaign this step belongs to.'),
    sa.Column('step_number', sa.Integer(), nullable=False, comment='Ordinal position in the email sequence (1 = first email, 2 = follow-up, …).'),
    sa.Column('subject_line', sa.String(length=998), nullable=False, comment='Email subject line for this step. Supports template variables.'),
    sa.Column('email_body', sa.Text(), nullable=False, comment='HTML or plain-text body of the email. Supports template variables.'),
    sa.Column('wait_days', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Days to wait after the previous step before sending this email.'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id'),
    sa.UniqueConstraint('campaign_id', 'step_number', name='uq_sequence_step_campaign_step')
    )
    op.create_table('email_event',
    sa.Column('event_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier for this event record.'),
    sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=False, comment='FK to lead — which contact this event is about.'),
    sa.Column('step_id', sa.UUID(as_uuid=False), nullable=False, comment='FK to sequence_step — which step triggered or is associated with this event.'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='Type of deliverability / engagement event (sent, opened, clicked, …).'),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when this event occurred.'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSONB payload with event-specific details (URLs, bounce codes, IPs, etc.).'),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.lead_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['sequence_step.step_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_event')
    op.drop_table('sequence_step')
    op.drop_table('lead')
    op.drop_table('warmup_settings')
    op.drop_table('collaborator_role')
    op.drop_table('campaign')
    op.drop_table('sender_account')
    op.drop_table('collaborator')
    op.drop_table('workspace')
    op.drop_table('refresh_tokens')
    op.drop_table('oauth_accounts')
    op.drop_table('local_auth')
    op.drop_table('users')
    op.drop_table('role')
    # ### end Alembic commands ###
