"""drop_owner_id_add_unique_constraints_fix_step_cascade

Revision ID: bcace0a892c7
Revises: 89b1d1781340
Create Date: 2026-04-23 13:02:27.612209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcace0a892c7'
down_revision: Union[str, None] = '89b1d1781340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_collaborator_workspace_user', 'collaborator', ['workspace_id', 'user_id'])
    op.alter_column('email_event', 'step_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='FK to sequence_step — NULL if the step has since been deleted.',
               existing_comment='FK to sequence_step — which step triggered or is associated with this event.')
    op.drop_constraint('email_event_step_id_fkey', 'email_event', type_='foreignkey')
    op.create_foreign_key(None, 'email_event', 'sequence_step', ['step_id'], ['step_id'], ondelete='SET NULL')
    op.create_unique_constraint('uq_lead_campaign_email', 'lead', ['campaign_id', 'email'])
    op.drop_column('local_auth', 'email_verified')
    op.create_unique_constraint('uq_oauth_provider_account', 'oauth_accounts', ['provider_type', 'provider_id'])
    op.drop_constraint('workspace_owner_id_fkey', 'workspace', type_='foreignkey')
    op.drop_column('workspace', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False, comment='FK to users — workspace owner/admin. RESTRICT prevents orphaned workspaces.'))
    op.create_foreign_key('workspace_owner_id_fkey', 'workspace', 'users', ['owner_id'], ['user_id'], ondelete='RESTRICT')
    op.drop_constraint('uq_oauth_provider_account', 'oauth_accounts', type_='unique')
    op.add_column('local_auth', sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='True once the user has clicked the email verification link.'))
    op.drop_constraint('uq_lead_campaign_email', 'lead', type_='unique')
    op.drop_constraint(None, 'email_event', type_='foreignkey')
    op.create_foreign_key('email_event_step_id_fkey', 'email_event', 'sequence_step', ['step_id'], ['step_id'], ondelete='CASCADE')
    op.alter_column('email_event', 'step_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='FK to sequence_step — which step triggered or is associated with this event.',
               existing_comment='FK to sequence_step — NULL if the step has since been deleted.')
    op.drop_constraint('uq_collaborator_workspace_user', 'collaborator', type_='unique')
    # ### end Alembic commands ###
