"""drop_owner_id_add_unique_constraints_fix_step_cascade

Revision ID: bcace0a892c7
Revises: 89b1d1781340
Create Date: 2026-04-23 13:02:27.612209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcace0a892c7'
down_revision: Union[str, None] = '89b1d1781340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_collaborator_workspace_user', 'collaborator', ['workspace_id', 'user_id'])
    op.alter_column('email_event', 'step_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='FK to sequence_step — NULL if the step has since been deleted.',
               existing_comment='FK to sequence_step — which step triggered or is associated with this event.')
    # Constraint name differs across environments (auto-generated by PostgreSQL),
    # so drop defensively.
    op.execute("ALTER TABLE email_event DROP CONSTRAINT IF EXISTS email_event_step_id_fkey")
    op.execute("ALTER TABLE email_event DROP CONSTRAINT IF EXISTS email_event_step_id_fkey_setnull")
    op.create_foreign_key(
        'email_event_step_id_fkey_setnull',
        'email_event',
        'sequence_step',
        ['step_id'],
        ['step_id'],
        ondelete='SET NULL',
    )
    op.create_unique_constraint('uq_lead_campaign_email', 'lead', ['campaign_id', 'email'])
    op.drop_column('local_auth', 'email_verified')
    op.create_unique_constraint('uq_oauth_provider_account', 'oauth_accounts', ['provider_type', 'provider_id'])
    op.execute("ALTER TABLE workspace DROP CONSTRAINT IF EXISTS workspace_owner_id_fkey")
    op.drop_column('workspace', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Keep rollback operable on real data: the old schema had NOT NULL owner_id,
    # but we cannot deterministically backfill an owner for existing rows.
    op.add_column(
        'workspace',
        sa.Column(
            'owner_id',
            sa.UUID(),
            autoincrement=False,
            nullable=True,
            comment='FK to users — workspace owner/admin. RESTRICT prevents orphaned workspaces.',
        ),
    )
    op.create_foreign_key('workspace_owner_id_fkey', 'workspace', 'users', ['owner_id'], ['user_id'], ondelete='RESTRICT')
    op.drop_constraint('uq_oauth_provider_account', 'oauth_accounts', type_='unique')
    op.add_column('local_auth', sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='True once the user has clicked the email verification link.'))
    op.drop_constraint('uq_lead_campaign_email', 'lead', type_='unique')
    # Support both legacy and newer DB states safely.
    op.execute("ALTER TABLE email_event DROP CONSTRAINT IF EXISTS email_event_step_id_fkey_setnull")
    op.execute("ALTER TABLE email_event DROP CONSTRAINT IF EXISTS email_event_step_id_fkey")
    # Before restoring NOT NULL + CASCADE, remove rows that became orphaned
    # when SET NULL semantics were active.
    op.execute("DELETE FROM email_event WHERE step_id IS NULL")
    op.create_foreign_key('email_event_step_id_fkey', 'email_event', 'sequence_step', ['step_id'], ['step_id'], ondelete='CASCADE')
    op.alter_column('email_event', 'step_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='FK to sequence_step — which step triggered or is associated with this event.',
               existing_comment='FK to sequence_step — NULL if the step has since been deleted.')
    op.drop_constraint('uq_collaborator_workspace_user', 'collaborator', type_='unique')
    # ### end Alembic commands ###
