"""
auth.py — Authentication and security utilities for CampaignPulse.

Responsibilities:
  1. Password hashing / verification via passlib (bcrypt).
  2. Email verification tokens via itsdangerous (signed, time-limited).
  3. JWT access token creation / decoding via python-jose.

Nothing in this module touches the database or FastAPI directly — it is a
pure utility layer that can be imported by any route handler or test.
"""

import os
from datetime import datetime, timedelta, timezone
from typing import Optional

import bcrypt as _bcrypt
from dotenv import load_dotenv
from itsdangerous import BadSignature, SignatureExpired, URLSafeTimedSerializer
from jose import JWTError, jwt  # noqa: F401  (re-exported for router imports)

# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------

_ENV_PATH = os.path.join(os.path.dirname(__file__), "..", "..", ".env")
load_dotenv(dotenv_path=_ENV_PATH)

SECRET_KEY: str = os.environ.get("SECRET_KEY", "")
ALGORITHM: str = os.environ.get("ALGORITHM", "HS256")
ACCESS_TOKEN_EXPIRE_MINUTES: int = int(os.environ.get("ACCESS_TOKEN_EXPIRE_MINUTES", 30))

if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is not set.")

# ---------------------------------------------------------------------------
# Password hashing  (bcrypt used directly — passlib 1.7.4 is incompatible
# with bcrypt >= 4.0 and raises ValueError for all passwords)
# ---------------------------------------------------------------------------


def hash_password(plain: str) -> str:
    """Return a bcrypt digest of the plain-text password."""
    return _bcrypt.hashpw(plain.encode("utf-8"), _bcrypt.gensalt()).decode("utf-8")


def verify_password(plain: str, hashed: str) -> bool:
    """
    Constant-time comparison of a plain-text password against its digest.
    Works correctly against hashes generated by either bcrypt or passlib.
    """
    return _bcrypt.checkpw(plain.encode("utf-8"), hashed.encode("utf-8"))


# ---------------------------------------------------------------------------
# Email verification tokens (itsdangerous)
# ---------------------------------------------------------------------------

# A dedicated salt separates verification tokens from any other signed data
# that might use the same SECRET_KEY in the future.
_email_serializer = URLSafeTimedSerializer(SECRET_KEY, salt="email-verification")
_account_link_serializer = URLSafeTimedSerializer(SECRET_KEY, salt="account-linking")

# Default token lifetime: 24 hours
VERIFICATION_TOKEN_MAX_AGE: int = 60 * 60 * 24
ACCOUNT_LINK_TOKEN_MAX_AGE: int = 60 * 60 * 24


def generate_verification_token(email: str) -> str:
    """
    Generate a cryptographically signed, URL-safe token that encodes the
    user's email address.  The token is self-validating (signature + expiry)
    so it does not need a separate database lookup to authenticate — although
    the route handler also checks the stored token for single-use enforcement.
    """
    return _email_serializer.dumps(email)


def decode_verification_token(token: str, max_age: int = VERIFICATION_TOKEN_MAX_AGE) -> str:
    """
    Decode a verification token and return the embedded email address.

    Raises:
        itsdangerous.SignatureExpired  — token is valid but past max_age.
        itsdangerous.BadSignature      — token is tampered or malformed.
    """
    return _email_serializer.loads(token, max_age=max_age)


def generate_account_link_token(email: str) -> str:
    """
    Generate a signed token for local-password linking on an existing OAuth account.
    """
    return _account_link_serializer.dumps(email)


def decode_account_link_token(token: str, max_age: int = ACCOUNT_LINK_TOKEN_MAX_AGE) -> str:
    """
    Decode account-link token and return email.
    """
    return _account_link_serializer.loads(token, max_age=max_age)


# Re-export so route handlers can catch these without importing itsdangerous.
__all__ = [
    "hash_password",
    "verify_password",
    "generate_verification_token",
    "decode_verification_token",
    "generate_account_link_token",
    "decode_account_link_token",
    "create_access_token",
    "decode_access_token",
    "SignatureExpired",
    "BadSignature",
    "JWTError",
]


# ---------------------------------------------------------------------------
# JWT access tokens (python-jose)
# ---------------------------------------------------------------------------


def create_access_token(
    data: dict,
    expires_delta: Optional[timedelta] = None,
) -> str:
    """
    Return a signed HS256 JWT containing the given claims plus an `exp` claim.

    Args:
        data:          Dict of claims to embed (typically {"sub": user_id, "email": ...}).
        expires_delta: Override the default token lifetime.  Defaults to
                       ACCESS_TOKEN_EXPIRE_MINUTES from the environment.
    """
    payload = data.copy()
    expire = datetime.now(timezone.utc) + (
        expires_delta if expires_delta is not None
        else timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    )
    payload["exp"] = expire
    return jwt.encode(payload, SECRET_KEY, algorithm=ALGORITHM)


def decode_access_token(token: str) -> dict:
    """
    Decode and verify a JWT access token.

    Raises:
        jose.JWTError — token is expired, malformed, or has an invalid signature.
    """
    return jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
